### PR TITLE
Bruchterme5

### PR DESCRIPTION
**Pull request by MathAdmin**

### CODE REVIEW

**Comment by MathAdmin** [comment]
const level = randomInt(1, 5);   Sollte nicht 1 sondern 0 sein.

**Comment by alimfeld** [comment]
Is this PR/branch still relevant? Otherwise I suggest to delete it.

**Comment by MathAdmin** [comment]
Not relevant any more. How can we delete it?

**Comment by alimfeld** [comment]
I closed the PR and deleted the branch.

**Comment by MathAdmin** [comment]
Merci

**Comment by MathAdmin** [comment]
Richtig 

Von meinem Xperia™ von Sony-Smartphone gesendet

---- alimfeld schrieb ----

**Pull request closed without merging**
